### PR TITLE
購買オーダに項目追加（買取担当者、作業時間）

### PR DESCRIPTION
**Pull request by TimLai125**

### CODE REVIEW

**Comment by TimLai125** [comment]
@yostashiro 

Yoshi, Can you try to pull the PR and test the 作業時間 field, I am not sure there is a strange error on my side that the field is always empty in the form view (The database has the new value though)

**Comment by yostashiro** [comment]
> Yoshi, Can you try to pull the PR and test the 作業時間 field, there is a strange error on my side that the field is always empty in the form view (The database has the new value though)

@TimLai125 

It looks OK to me.

image

**Comment by yostashiro** [comment]
@TimLai125 

Here is my genius solution:

```
    worked_hours = fields.Selection(
        # [(num/2, str(num/2) + ' hours') for num in range(1, 21)],
        [(num, str(num) + ' hours') for num in ['0.5', '1.0', '1.5', '2.0',
                                                '2.5', '3.0', '3.5', '4.0',
                                                '4.5', '5.0', '5.5', '6.0',
                                                '6.5', '7.0', '7.5', '8.0',
                                                '8.5', '9.0', '9.5', '10.0']],
        string='Worked Hours',
    )
```

**Comment by TimLai125** [comment]
@yostashiro But what's problematic in my previous solution?

**Comment by yostashiro** [comment]
> But what's problematic in my previous solution?

@TimLai125 It probably has to do with the fact that `num` being an integer.

This https://stackoverflow.com/questions/477486/how-to-use-a-decimal-range-step-value/477635#477635 would be a good option but we need to add the dependency, so I thought we might go with the way I suggested.

**Pull request merged**
